name: Build vllm CPU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-docker-action@v4.6.0
      - run: git clone https://github.com/vllm-project/vllm
      - run: |
          cd vllm
          docker build -f Dockerfile.cpu -t vllm-cpu --shm-size=4g . -o type=docker,name=vllm-cpu,dest=/tmp/vllm.tar
      #- run: docker save vllm-cpu > /tmp/vllm.tar
      - run: gzip /tmp/vllm.tar
      - uses: actions/upload-artifact@v5.0.0
        with:
          path: /tmp/vllm.tar.gz
